print("Shylaja", "Welcome", 123, 3.6, "True", True, sep='-')
print("Shylaja", "Welcome", 123, 3.6, "True", True, sep='@')
print("Shylaja", "Welcome", 123, 3.6, "True", True, sep='-', end='\n')
print("Shylaja")
print("Shylaja", "Welcome", 123, 3.6, "True", True, sep='-', end='_')
print("Shylaja")
print("Shylaja", "Welcome", 123, 3.6, "True", True, end='_')
print("Shylaja")
